import type { GameType } from "../types";
import type { EntityType } from "../entities/EntitiesTypes";
import { recipe1 } from "../entities/Exchanger/recipes";

export const exchangerConsumerData: GameType = {
  entities: new Map<string, EntityType>([
    [
      "source1",
      {
        id: "source1",
        name: "Source 1",
        type: "source",
        goodType: "red",
        max: 5,
        rate: 1,
        cooldown: 0,
        x: 2,
        y: 2,
        leavingDirection: "down",
        goods: [],
      },
    ],
    [
      "consumer1",
      {
        id: "consumer1",
        name: "Consumer 1",
        type: "consumer",
        max: 2,
        rate: 1,
        cooldown: 0,
        x: 7,
        y: 4,
        entryDirection: "up",
        goods: [],
      },
    ],

    [
      "merger1",
      {
        id: "merger1",
        name: "Merger 1",
        type: "merger",
        max: 1,
        rate: 1,
        cooldown: 0,
        leavingDirection: "right",
        x: 2,
        y: 3,
        target: "transport1",
        sources: ["source3", "source2", "source1"],
        nextSourceIndex: 0,
        movingGoods: [],
        goods: [],
      },
    ],
    [
      "source2",
      {
        id: "source2",
        name: "Source 2",
        type: "source",
        goodType: "red",
        max: 5,
        rate: 1,
        cooldown: 0,
        x: 1,
        y: 3,
        leavingDirection: "right",
        goods: [],
      },
    ],
    [
      "source3",
      {
        id: "source3",
        name: "Source 3",
        type: "source",
        goodType: "blue",
        max: 5,
        rate: 1,
        cooldown: 0,
        x: 2,
        y: 4,
        leavingDirection: "up",
        goods: [],
      },
    ],
    [
      "transport1",
      {
        id: "transport1",
        name: "Transport 1",
        type: "transport",
        max: 1,
        rate: 1,
        cooldown: 0,
        source: "merger1",
        target: "transport3",
        x: 3,
        y: 3,
        entryDirection: "left",
        leavingDirection: "right",
        movingGoods: [],
        goods: [],
      },
    ],
    [
      "transport3",
      {
        id: "transport3",
        name: "Transport 3",
        type: "transport",
        max: 1,
        rate: 1,
        cooldown: 0,
        source: "transport1",
        target: "exchanger1",
        x: 4,
        y: 3,
        entryDirection: "left",
        leavingDirection: "right",
        goods: [],
        movingGoods: [],
      },
    ],
    [
      "stock1",
      {
        id: "stock1",
        name: "Stock 1",
        type: "stock",
        max: 10,
        closed: false,
        x: 6,
        y: 3,
        direction: "right",
        goods: [],
      },
    ],
    [
      "transport2",
      {
        id: "transport2",
        name: "Transport 2",
        type: "transport",
        max: 1,
        rate: 1,
        cooldown: 0,
        source: "stock1",
        target: "consumer1",
        x: 7,
        y: 3,
        entryDirection: "left",
        leavingDirection: "down",
        movingGoods: [],
        goods: [],
      },
    ],
    [
      "exchanger1",
      {
        id: "exchanger1",
        name: "Exchanger 1",
        type: "exchanger",
        recipe: recipe1,
        direction: "right",
        source: "transport3",
        target: "stock1",
        x: 5,
        y: 3,
        movingGoods: [],
        goods: [],
      },
    ],
  ]),
  selected: null,
  status: "waiting",
  stocks: ["stock1"],
  sources: ["source1", "source2", "source3"],
  consumers: ["consumer1"],
  transports: ["transport1", "transport2", "transport3"],
  splitters: [],
  exchangers: ["exchanger1"],
  mergers: ["merger1"],
  editor: null,
  time: 0,
  data: "exchanger consumer",
};
