import type { GameType } from "../GameTypes";
import type { EntityType } from "../entities/EntitiesTypes";
import { recipe1 } from "../entities/Exchanger/Recipes/recipes";

export const mergerComplexoData: GameType = {
  entities: new Map<string, EntityType>([
    [
      "source1",
      {
        id: "source1",
        name: "Source 1",
        type: "source",
        goodType: "blue",
        max: 5,
        rate: 1,
        cooldown: 0,
        x: 3,
        y: 2,
        leavingDirection: "down",
        goods: [],
      },
    ],
    [
      "merger1",
      {
        id: "merger1",
        name: "Merger 1",
        type: "merger",
        max: 1,
        rate: 1,
        cooldown: 0,
        leavingDirection: "right",
        x: 3,
        y: 3,
        target: "merger2",
        sources: ["source3", "source2", "source1"],
        nextSourceIndex: 0,
        movingGoods: [],
        goods: [],
      },
    ],
    [
      "merger2",
      {
        id: "merger2",
        name: "Merger 2",
        type: "merger",
        max: 1,
        rate: 1,
        cooldown: 0,
        leavingDirection: "down",
        x: 4,
        y: 3,
        target: "transport1",
        sources: ["merger1", "transport2", "source5"],
        nextSourceIndex: 0,
        movingGoods: [],
        goods: [],
      },
    ],
    [
      "source2",
      {
        id: "source2",
        name: "Source 2",
        type: "source",
        goodType: "red",
        max: 5,
        rate: 1,
        cooldown: 0,
        x: 2,
        y: 3,
        leavingDirection: "right",
        goods: [],
      },
    ],
    [
      "source3",
      {
        id: "source3",
        name: "Source 3",
        type: "source",
        goodType: "red",
        max: 5,
        rate: 1,
        cooldown: 0,
        x: 3,
        y: 4,
        leavingDirection: "up",
        goods: [],
      },
    ],
    [
      "source4",
      {
        id: "source4",
        name: "Source 4",
        type: "source",
        goodType: "red",
        max: 5,
        rate: 1,
        cooldown: 0,
        x: 4,
        y: 1,
        leavingDirection: "down",
        goods: [],
      },
    ],
    [
      "transport1",
      {
        id: "transport1",
        name: "Transport 2",
        type: "transport",
        max: 1,
        rate: 1,
        cooldown: 1,
        source: "merger2",
        target: "consumer1",
        x: 4,
        y: 4,
        entryDirection: "up",
        leavingDirection: "down",
        movingGoods: [],
        goods: [],
      },
    ],
    [
      "transport2",
      {
        id: "transport2",
        name: "Transport 2",
        type: "transport",
        max: 1,
        rate: 1,
        cooldown: 1,
        source: "source4",
        target: "merger2",
        x: 4,
        y: 2,
        entryDirection: "up",
        leavingDirection: "down",
        movingGoods: [],
        goods: [],
      },
    ],
    [
      "consumer1",
      {
        id: "consumer1",
        name: "Consumer 1",
        type: "consumer",
        max: 2,
        rate: 1,
        cooldown: 0,
        x: 4,
        y: 5,
        entryDirection: "up",
        goods: [],
      },
    ],
    [
      "source5",
      {
        id: "source5",
        name: "Source 5",
        type: "source",
        goodType: "red",
        max: 5,
        rate: 1,
        cooldown: 0,
        x: 5,
        y: 3,
        leavingDirection: "left",
        goods: [],
      },
    ],
  ]),
  selected: null,
  status: "waiting",
  stocks: [],
  sources: ["source1", "source2", "source3", "source4", "source5"],
  consumers: ["consumer1"],
  transports: ["transport1", "transport2"],
  splitters: [],
  exchangers: [],
  mergers: ["merger1", "merger2"],
  editor: null,
  time: 0,
  data: "merger complexo",
  recipe: recipe1,
};
