import type { GameType } from "../GameTypes";
import type { EntityType } from "../entities/EntitiesTypes";
import { recipe1 } from "../entities/Exchanger/Recipes/recipes";

export const splitterSimplesData: GameType = {
  entities: new Map<string, EntityType>([
    [
      "stock1",
      {
        id: "stock1",
        name: "Stock 1",
        type: "stock",
        max: 10,
        closed: false,
        x: 4,
        y: 3,
        direction: "right",
        goods: [],
      },
    ],
    [
      "source1",
      {
        id: "source1",
        name: "Source 1",
        type: "source",
        goodType: "blue",
        max: 5,
        rate: 1,
        cooldown: 0,
        x: 3,
        y: 2,
        leavingDirection: "down",
        goods: [],
      },
    ],

    [
      "splitter1",
      {
        id: "splitter1",
        name: "Splitter 1",
        type: "splitter",
        max: 2,
        rate: 1,
        cooldown: 0,
        entryDirection: "up",
        x: 3,
        y: 3,
        source: "source1",
        targets: ["stock1", "transport1", "consumer1"],
        nextTargetIndex: 0,
        movingGoods: [],
        goods: [],
      },
    ],

    [
      "consumer1",
      {
        id: "consumer1",
        name: "Consumer 1",
        type: "consumer",
        max: 2,
        rate: 1,
        cooldown: 0,
        x: 2,
        y: 3,
        entryDirection: "right",
        goods: [],
      },
    ],
    [
      "transport1",
      {
        id: "transport1",
        name: "Transport 1",
        type: "transport",
        max: 1,
        rate: 1,
        cooldown: 1,
        source: "splitter1",
        target: "consumer2",
        x: 3,
        y: 4,
        entryDirection: "up",
        leavingDirection: "down",
        movingGoods: [],
        goods: [],
      },
    ],
    [
      "consumer2",
      {
        id: "consumer2",
        name: "Consumer 2",
        type: "consumer",
        max: 2,
        rate: 1,
        cooldown: 0,
        x: 3,
        y: 5,
        entryDirection: "up",
        goods: [],
      },
    ],
  ]),
  selected: null,
  status: "waiting",
  stocks: ["stock1"],
  sources: ["source1"],
  consumers: ["consumer1", "consumer2"],
  transports: ["transport1"],
  splitters: ["splitter1"],
  mergers: [],
  exchangers: [],
  editor: null,
  time: 0,
  data: "splitter simples",
  recipe: recipe1,
};
