import type { GameType } from "./types";
import type {
  EntityType,
} from "./entities/EntitiesTypes"

export const initialState: GameType = {
  entities: new Map<string, EntityType>([
    [
      "source1",
      {
        id: "source1",
        name: "Source 1",
        type: "source",
        val: 0,
        max: 5,
        rate: 1,
        cooldown: 0,
        x: 0,
        y: 0,
      },
    ],
    [
      "consumer1",
      {
        id: "consumer1",
        name: "Consumer 1",
        type: "consumer",
        val: 0,
        max: 2,
        rate: 0.8,
        cooldown: 0,
        x: 2,
        y: 0,
      },
    ],
    [
      "transport1",
      {
        id: "transport1",
        name: "Transport 1",
        type: "transport",
        val: 0,
        max: 1,
        rate: 0.25,
        cooldown: 1,
        source: "source1",
        target: "consumer1",
        x: 1,
        y: 0,
        direction: "right",
      },
    ],
    [
      "transport2",
      {
        id: "transport2",
        name: "Transport 2",
        type: "transport",
        val: 0,
        max: 1,
        rate: 0.5,
        cooldown: 1,
        source: "source1",
        target: "stock1",
        x: 0,
        y: 1,
        direction: "down",
      },
    ],
    [
      "stock1",
      {
        id: "stock1",
        name: "Stock 1",
        type: "stock",
        val: 0,
        max: 10,
        closed: false,
        x: 0,
        y: 2,
      },
    ],
  ]),
  selected: null,
  status: "waiting",
  stocks: ["stock1"],
  sources: ["source1"],
  consumers: ["consumer1"],
  transports: ["transport1", "transport2"],
};
