import type { GameType } from "./types";
import type { EntityType } from "./entities/EntitiesTypes";

export const initialState3: GameType = {
  entities: new Map<string, EntityType>([
    [
      "source1",
      {
        id: "source1",
        name: "Source 1",
        type: "source",
        goodType: "red",
        max: 5,
        rate: 1,
        cooldown: 0,
        x: 0,
        y: 0,
        leavingDirection: "right",
        goods: [],
      },
    ],
    [
      "consumer1",
      {
        id: "consumer1",
        name: "Consumer 1",
        type: "consumer",
        max: 2,
        rate: 1,
        cooldown: 0,
        x: 2,
        y: 0,
        entryDirection: "left",
        goods: [],
      },
    ],
    [
      "transport1",
      {
        id: "transport1",
        name: "Transport 1",
        type: "transport",
        max: 1,
        rate: 1,
        cooldown: 1,
        source: "source1",
        target: "consumer1",
        x: 1,
        y: 0,
        entryDirection: "left",
        leavingDirection: "right",
        movingGoods: [],
        goods: [],
      },
    ],

    
    [
      "source2",
      {
        id: "source2",
        name: "Source 2",
        type: "source",
        goodType: "blue",
        max: 5,
        rate: 1,
        cooldown: 0,
        x: 3,
        y: 2,
        leavingDirection: "down",
        goods: [],
      },
    ],

    [
      "merger1",
      {
        id: "merger1",
        name: "Merger 1",
        type: "merger",
        max: 1,
        rate: 1,
        cooldown: 0,
        leavingDirection: "right",
        x: 3,
        y: 3,
        target: "merger2",
        source: [null, "source3", "source2"],
        nextSourceIndex: 0,
        movingGoods: [],
        goods: [],
      },
    ],
    [
      "merger2",
      {
        id: "merger2",
        name: "Merger 2",
        type: "merger",
        max: 1,
        rate: 1,
        cooldown: 0,
        leavingDirection: "down",
        x: 4,
        y: 3,
        target: "transport2",
        source: ["merger1", "transport3", "source6"],
        nextSourceIndex: 0,
        movingGoods: [],
        goods: [],
      },
    ],
    [
      "source3",
      {
        id: "source3",
        name: "Source 3",
        type: "source",
        goodType: "red",
        max: 5,
        rate: 1,
        cooldown: 0,
        x: 2,
        y: 3,
        leavingDirection: "right",
        goods: [],
      },
    ],
    [
      "source4",
      {
        id: "source4",
        name: "Source 4",
        type: "source",
        goodType: "red",
        max: 5,
        rate: 1,
        cooldown: 0,
        x: 3,
        y: 4,
        leavingDirection: "up",
        goods: [],
      },
    ],
    [
      "source5",
      {
        id: "source5",
        name: "Source 5",
        type: "source",
        goodType: "red",
        max: 5,
        rate: 1,
        cooldown: 0,
        x: 4,
        y: 1,
        leavingDirection: "down",
        goods: [],
      },
    ],
    [
      "transport2",
      {
        id: "transport2",
        name: "Transport 2",
        type: "transport",
        max: 1,
        rate: 1,
        cooldown: 1,
        source: "merger2",
        target: "consumer2",
        x: 4,
        y: 4,
        entryDirection: "up",
        leavingDirection: "down",
        movingGoods: [],
        goods: [],
      },
    ],
    [
      "transport3",
      {
        id: "transport3",
        name: "Transport 3",
        type: "transport",
        max: 1,
        rate: 1,
        cooldown: 1,
        source: "source5",
        target: "merger2",
        x: 4,
        y: 2,
        entryDirection: "up",
        leavingDirection: "down",
        movingGoods: [],
        goods: [],
      },
    ],
    [
      "consumer2",
      {
        id: "consumer2",
        name: "Consumer 2",
        type: "consumer",
        max: 2,
        rate: 1,
        cooldown: 0,
        x: 4,
        y: 5,
        entryDirection: "up",
        goods: [],
      },
    ],
    [
      "source6",
      {
        id: "source6",
        name: "Source 6",
        type: "source",
        goodType: "red",
        max: 5,
        rate: 1,
        cooldown: 0,
        x: 5,
        y: 3,
        leavingDirection: "left",
        goods: [],
      },
    ],
    
  ]),
  selected: null,
  status: "waiting",
  stocks: [],
  sources: ["source1", "source2","source3","source4","source5","source6"],
  consumers: ["consumer1", "consumer2"],
  transports: ["transport1", "transport2","transport3"],
  splitters: [],
  mergers: ["merger1", "merger2"],
  editor: null,
  time: 0,
};
